import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Artisan Ceramic Mug',
    description: 'Handcrafted ceramic mug, perfect for your morning coffee or tea. Unique glaze finish.',
    price: 24.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Homeware',
    stock: 15,
    dataAiHint: 'ceramic mug',
  },
  {
    id: '2',
    name: 'Abstract Canvas Print',
    description: 'Modern abstract art print on high-quality canvas. Adds a touch of sophistication to any room.',
    price: 79.50,
    imageUrl: 'https://placehold.co/400x500.png',
    category: 'Wall Art',
    stock: 8,
    dataAiHint: 'abstract art',
  },
  {
    id: '3',
    name: 'Minimalist Desk Lamp',
    description: 'Sleek and modern desk lamp with adjustable arm. Provides focused lighting for work or study.',
    price: 45.00,
    imageUrl: 'https://placehold.co/500x450.png',
    category: 'Lighting',
    stock: 20,
    dataAiHint: 'desk lamp',
  },
  {
    id: '4',
    name: 'Organic Cotton Throw',
    description: 'Soft and cozy throw blanket made from 100% organic cotton. Ideal for chilly evenings.',
    price: 59.99,
    imageUrl: 'https://placehold.co/600x450.png',
    category: 'Textiles',
    stock: 12,
    dataAiHint: 'cotton throw',
  },
  {
    id: '5',
    name: 'Sculptural Bud Vase',
    description: 'Elegant bud vase with a unique sculptural design. A beautiful centerpiece for small floral arrangements.',
    price: 32.00,
    imageUrl: 'https://placehold.co/450x550.png',
    category: 'Decor',
    stock: 18,
    dataAiHint: 'bud vase',
  },
  {
    id: '6',
    name: 'Designer Fountain Pen',
    description: 'A premium fountain pen for a smooth writing experience. Timeless design and craftsmanship.',
    price: 120.00,
    imageUrl: 'https://placehold.co/550x400.png',
    category: 'Stationery',
    stock: 5,
    dataAiHint: 'fountain pen',
  },
];
